-- phpMyAdmin SQL Dump
-- version 4.3.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: May 12, 2015 at 07:54 PM
-- Server version: 5.6.24
-- PHP Version: 5.6.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `jowa`
--

-- --------------------------------------------------------

--
-- Table structure for table `jowa_videos`
--

CREATE TABLE IF NOT EXISTS `jowa_videos` (
  `id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `position` bigint(20) unsigned NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `lenght_seconds` int(10) unsigned NOT NULL,
  `id_youtube` varchar(255) NOT NULL,
  `ts_uploaded` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `jowa_videos`
--

INSERT INTO `jowa_videos` (`id`, `user_id`, `position`, `title`, `description`, `lenght_seconds`, `id_youtube`, `ts_uploaded`) VALUES
(1, 1, 1, 'GetVerifiedStatus PayPal [withArtur]obiv.it', ' ', 240, 'ZyaMJPxw6Ow', '2015-04-21 23:28:49'),
(2, 1, 2, 'Dlia mami Soxraniaem vidio v Camtasia [OBIV].it', 'Kak saxraniat vidio v Camtasia Studio 8 ', 240, 'XguudcJ3vHY', '2015-04-21 23:29:57'),
(3, 1, 3, '#MVC in #PHP 18 - Git, Branch, Twitter Bootstrap [withArtur]obiv.it', 'E non perdetevi http://www.healtheye.it \nIl portale sulla Sanità, fatto per tutti voi!\n\nVideoCorso #MVC in #PHP Continuiamo a vedere che cose la version control, perche e a che cosa serve come puo presentarsi utile ...\nQuesta volta vediamo che cosa sono i branch, come aiutano a collaborare un team di sviluppatori e come possono rendersi utili anche per una singola persona.\nVediamo inoltre come realizzare la funzionalità di creazione pagina e come implementare, come funziona e che cos''è Twitter Bootstrap.\n\nCodice MVC in PHP:\nhttps://github.com/arturmamedov/mvc_in_php\n\nNuovo Canale: \nhttps://www.youtube.com/channel/UCUZwpmxce42g_9wwjuuyAsg\n\nLe ultimissime:\nhttp://witharturblog.tumblr.com/ ', 240, 'qFtMKCcT_q4', '2015-04-21 23:29:57'),
(4, 1, 4, '#MVC in #PHP 19 - Riprendiamo e Git, Github, Clone, Commit [withArtur]obiv.it', 'E non perdetevi http://www.healtheye.it\n\nVideoCorso #MVC in #PHP Riprendiamo da dove eravamo rimasti ma sta volta con Git, Github, Clone, Commit ... Vediamo che cose la version control, perche e a che cosa serve come puo presentarsi utile ...\nRisolviamo gli errori PHP di MVC in PHP e imapariamo che cose Git e Github e come usarli per il proprio codice del progetto. \nhttps://github.com\n\nCodice MVC in PHP:\nhttps://github.com/arturmamedov/mvc_in_php\n\nNuovo Canale: \nhttps://www.youtube.com/channel/UCUZwpmxce42g_9wwjuuyAsg\n\nLe ultimissime:\nhttp://witharturblog.tumblr.com/ ', 240, '2UQAldSQ03w', '2015-04-21 23:29:57'),
(5, 1, 5, 'HealthEye General Test at 09072014', 'Artur Mamedov testing HealthEye applications in Chrome, Firefox, Opera, InternetExplorer, Safari for Windows ... Testing Flow of registration, email confirmation, login, change password, password recovery, facebook connect. User settings, address. \n\nWrite review , Write review without login and after authenticate. ', 240, 'qigI0Zs5VoU', '2015-04-21 23:29:57'),
(6, 1, 6, 'CasaVenditaImmobili - Applicazione, SSD - Piga, Mamedov', 'Introduzione nel funzionamento dell''applicazione CVI realizzata con Zend1.12 , MVC, Smarty 3.x, jQuery, AngularJS , Bootstrap 3.x e altro\n\nLink utili:\n-- Link di SSD: http://www.casavenditaimmobili.com/property/xml?number=\n\n-- Link Documento: https://docs.google.com/document/d/1uP63wC939HgC2pi6nt1VQ2S7xxjiFKxbpCnR4B8AevY/edit?usp=sharing\n\nLink documento del da fare: https://docs.google.com/document/d/17IAyMn2flXa6pBv0VxsjZLNLrd5FR5plpllQeqwVB1o/edit?usp=sharing\n\nDocumento con tanti link utili:\nhttps://docs.google.com/presentation/d/1iE3D6VwRszk9Zfu75c2Yq8rBrvz_r0Aq_UAj0D5VIdA/edit?usp=sharing\n\nUn altro doc con tanti link:\n!important\nhttps://www.evernote.com/shard/s356/sh/afbeb099-8af5-4144-8cd0-f40426e337bf/fbb4d7cf49c7e2f98dec8e3de96570c4\n\nSSD agenzie:\n1 - https://www.evernote.com/shard/s356/sh/11204abf-316b-41b8-823f-d42813e85174/bf1f0ec3d0ac56079452c6a1178e3f4b\n2 - https://www.evernote.com/shard/s356/sh/5a3db010-27b6-4f00-9212-593883a3c8c5/e0d1fed8899cbcb348c7089907dd4eba ', 240, 'nGBeHYSqLh4', '2015-04-21 23:29:57'),
(7, 1, 7, 'Ciao Davide e Gabriella :) Artur Mamedov', 'Video privato: Nel quale faccio una presentazione di come funziona il sito nelle basi, cosi possiamo assieme capire e parlare di cosa abbiamo bisogna ora, quali dettagli, quali funzionalita, come deve essere l''esperienza degli utenti e degli amministratori... ', 240, 'xDTcG0FKkXM', '2015-04-21 23:29:57'),
(8, 1, 8, 'аиде с любовью', 'я тебя люблю ', 240, 'GKYw4pgk9Ns', '2015-04-21 23:29:57'),
(9, 1, 9, 'Casa Vendita Immobili - Fine Maggio (Utenti) by Artur Mamedov', 'Ciao Gavino, le nove di ieri sera intendevo, invece sono diventate le 9 di sta mattina.\n\nNon so come la prendi, spero non male, alla fine secondo me ci fissiamo troppo su questo appuntamento e ci va sempre male, non lo diceva anche il libro che finche vuoi una cosa non l''avrai appena lascia andare eccola.\n\nBellissimo quel libro :) ti ringrazio ancora.\n\nComunque ecco il video con un po gli aggiornamenti che o fatto, un altra sfiga che ho avuto e'' che si e'' registrato male sto video :( ma si vede abbastanza e si sente.\n\nhttp://youtu.be/SzOkBr9SUeQ\n\nNel video ti mostro le impostazioni utente che ora vanno a tipologia account Privato, Agenzia Immobiliare ...\nLa pagina profilo degli utenti\n\nE propongo di inviare una mail a quelli di SSD chiedendo gentilmente il loro logo come risposta senza venire ancora sul sito, cosi noi inseriamo il loro logo manualmente poi gli mandiamo il link alla pagina, loro vedono e vedono che si puo mettere anche il link sociale tipo Fb, Twitter etc. e questo potrbbe incentivarli a richiedere password etc.\nEsempio pagine:\nhttp://www.casavenditaimmobili.com/u/giovanna\nhttp://www.casavenditaimmobili.com/u/gbrokers con logo\n\n\nPoi facio vedere cosa ho fatto per la gestione utenti che ancora e'' da finire, li ho solo divisi, ora mi manca la mail e la divisione per regioni citta etc. che facio in modo piu'' intuitivo di come ti dico li, e altre funzionalita'' come nota sul utente e la possibilita'' di cestinare (meglio di eliminare direttamente). Un altra settimana minimo di tempo.\n\nDimmi quando vuoi appuntamento tu, visto che il buco l''ho dato io, oppure io ti riesco a dare nuove notizie martedi.\n\nP.S. Da SSD e'' arrivata un agenzia immobiliare che vedo dal vivo :))))) con 50 annunci di vendita.\nP.S.S. Se ti piace il video formato, ti posso fare anche video guide di cose tecniche :))) se sei fanatico come me xD\n\nBuona giornata Gavino, Artur. ', 240, 'SzOkBr9SUeQ', '2015-04-21 23:29:57'),
(10, 1, 10, 'Iniziamo con #Javascript (ancora inedita,da migliorare) [withArtur] obiv.it', 'Iniziamo con Javascript! Quale la sua storia, visto che io adoro la storia e poi BASI del js per vedere che la sintassi e'' simile al C e al  PHP. \nVediamo come definire variabili\nCome fare condizioni\nCome fare i Cicli (while)\ne se non sbaglio i tipi di dati \nwithJavascript\n\nNode.js discussione su FB: https://www.facebook.com/withArtur/posts/569737109728608\n\nPer approfondire di piu'' molto di piu'' su js: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference\n\nOra lo sto rifacendo molto più dettagliato\nhttp://www.obiv.it/\n\nArtur Mamedov (withArtur)\nhttps://www.facebook.com/withArtur ', 240, 'mD05NySS5QU', '2015-04-21 23:29:57'),
(11, 1, 11, 'quickMVC - Recupero dati e visualizzazione con mini Framework [withArtur]', 'Compito dopo la prima lezione sul MVC in PHP.\n- metiamo in pratica creando la tabella nel database, il model che gestisce i dati, il controller per legare il model alla vista e la vista :)\n\nRiepilogo lezione file in drive: http://goo.gl/WsZsJe\nPer gli interessati al archivio di codice usato, aspetto nei commenti poi provvedero il link da qaulche parte :)\n\nhttp://obiv.it/ ', 240, 'MjsQ-Hi1MsE', '2015-04-21 23:29:57'),
(12, 1, 12, 'Database tier (RDBMS, SQL)[withArtur]', 'Il livello che sta alla base di tutta l''architettura. Come funziona il database, di cosa e'' composto ... Perché? Come? E quando lo \nscopriamo in meno di 5 minuti e diciamo anche qual''è quello che util ', 240, 'llNoXBURtGc', '2015-04-21 23:29:57'),
(13, 1, 13, 'Middle tier (Server) - [withArtur]', 'Il server web gioca un ruolo molto importante nell''architettura e lui che si \noccupa e prende la responsabilità dei compiti più difficili. Vediamo come fa , \nquale tecnologie usa e qual''è il server web che utilizzeremo noi nel video \ncorso.\n\n\nSito ufficiale: http://obiv.it/\nFacebook: http://obiv.it/index/urlfb\nArtur Mamedov ', 240, 'oNXBYpUqV8s', '2015-04-21 23:29:57'),
(14, 1, 14, 'Client tier (Browser) - [withArtur]', 'Abbiamo visto come interagiscono i vari livelli tra di loro nella video lezione \nprecedente ed è arrivata l''ora di esaminare ogni livello a parte. Partendo dal \nbrowser, il client tier, scopriamo che linguaggi supporta, come è chiamato in \nalternativa, come si collega e quale scelgo io per il video corso.\n\n\nSito ufficiale: http://obiv.it/\nFacebook: http://obiv.it/index/urlfb\nArtur Mamedov ', 240, 'KFJ4xHBV34M', '2015-04-21 23:29:57'),
(15, 1, 15, 'Intro nell''architettura del WEB - [withArtur]', 'Come funziona l''interazione tra un browser e un server web? Che differenza \nc''è tra una richiesta di file statico .html e file dinamico .php ? Che ruolo gioca \nil Database nel web ? E altre risposte alle domande sull''architettura che ha il \nweb, quali sono i livelli e come funziona/che funzione hanno.\n\n\nSito ufficiale: http://obiv.it/\nFacebook: http://obiv.it/index/urlfb\nArtur Mamedov ', 240, 'MrsYt6_WY2o', '2015-04-21 23:29:57'),
(16, 1, 16, 'URL (Uniform Resource Locator) [withArtur]', 'Un URL è una parte fondamentale per il web, identifica una risorsa \nspecificando con che dominio è raggiungibile. E bisogna sapere come si \nscompone un URL, che differenza c''è tra URL assoluta e URL relativa. Cosa \nsono i parametri di un URL. E tutto questo e altro lo speigo in questo video \nlezione.\n\nSito ufficiale: http://obiv.it/\nFacebook: http://obiv.it/index/urlfb\nArtur Mamedov ', 240, 'Lw-vQa4mlDc', '2015-04-21 23:29:57'),
(17, 1, 17, 'Protocolli TCP/IP (Transmission Control Protocol/Internet Protocol) [withArtur]', 'Alla base di tutte le connessioni stabili e sicure troviamo TCP e IP due \nprotocolli internet che si occupano del instradamento e del invio di dati nella \nrete. In questa video lezione vediamo come funzionano a cosa servono e \ntutto quello che li riguarda.\n\n\nSito ufficiale: http://obiv.it/\nFacebook: http://obiv.it/index/urlfb\nArtur Mamedov ', 240, 'HVHMwwqtXgw', '2015-04-21 23:29:57'),
(18, 1, 18, 'Protocollo HTTP (Hypertext Transfer Protocol) [withArtur]', 'Sicuramente sapete che per scrivere un URL bisogna scrivere '' http:// ... '' \nd''avanti e solo dopo il resto. E scrivendo cosi non facciamo altro che \nspecificare il protocollo. HTTP è un protocollo WEB che si appoggia su TCP/IP \ne funziona a richiesta risposta ed è importante capirlo per riuscire a fare \npagine web dinamiche complete e sicure.\n\nSito ufficiale: http://obiv.it/\nFacebook: http://obiv.it/index/urlfb\nArtur Mamedov ', 240, 'cYmT4ZDcj40', '2015-04-21 23:29:57'),
(19, 1, 19, 'Cookie e Cache [withArtur]', 'Molti fanno confusione tra questi due elementi del WEB, anzi sono elementi \ndel browser. Perché il browser ha bisogno di memorizzare dei dati, in questo \nmodo il suo lavoro con il server viene ottimizzato e il protocollo HTTP può \ndiventare state-full.\n\nSito ufficiale: http://obiv.it/\nFacebook: http://obiv.it/index/urlfb\nArtur Mamedov ', 240, 'ZCpdUMA1fcM', '2015-04-21 23:29:57'),
(20, 1, 20, 'The Chemical Brothers 01/06/2013 Coccorico - Ricione (Italy)', 'Ed e Simon a un metro e mezzo da me, e il top, io che applaudo con il cellulare in mano mentre riprendo. Track: Swon \n\nDon''t forget \nTo fall in love\nThere nothing else ', 240, 'ze6ee9KWsf4', '2015-04-21 23:29:57'),
(21, 1, 21, 'Io in snowboard su una pista chiusa al monte Cimone', 'La pista 8 che era chiusa quest''anno a me mi e'' piaciuta piu'' di tutto ', 240, 'kYuXBRAiKr0', '2015-04-21 23:29:57'),
(22, 1, 22, 'Intro VideoGiornale 9 (Conto alla Rovescia, Neve sul Sito) [OBIV].it', 'Ed ecco un altro numero del Video Giornale [OBIV].it di me Artur Mamedov :)\nNel quale parleremo di temi festivi come la conta al rovescio, che vediamo in due modi: \n- conta al rovescio in PHP \n- conta al rovescio in jQuery\ne poi vediamo come far nevicare sul sito in modo molto bello adirituura potremo mettere che i fiocchi di neve siano dei link.\n\nComunque nel video racconto tutto, buona visione e buone feste :)\n\nhttp://www.obiv.it ', 240, 'CcJHnVpgWwY', '2015-04-21 23:29:57'),
(23, 1, 23, 'Presentazione Video Corso "PHP: Hypertext Preprocessor" Artur Mamedov [OBIV].it', '"PHP: Hypertext Preprocessor" | Artur Mamedov - [OBIV].it\nPiù di 50 Video Lezioni, 16 ore di video, di cui 4 ore sono dedicati alla pratica con esempi per accumulare tutto il funzionale del corso e capire in questo modo come si applica quello che studiamo "nella vita reale". \nIl video corso che non si è fatto sfugire nulla! \n\nCompleto ed efficace per imparare il PHP bene e una volta per tutte!\n\nhttp://witharturblog.tumblr.com/post/97369338183/artur-mamedov-videolezioni-videocorsi-withartur ', 240, '95PgFdq9ZOs', '2015-04-21 23:29:57'),
(24, 1, 24, 'CSS Sprites Parte3 (Scriviamo il codice HTML e CSS per il menu) [OBIV].it', 'Nella terza Videolezione sui CSS Sprites , http://obiv.it/video-giornale/6-css-sprites-menu.html , scriviamo il codice HTML e CSS necessario per far funzionare il nostro menu Image Sprites. Creeremo una pagina HTML con un ''nav'' e un ''ul'' al interno del quale i tag ''li'' con i link alle pagine, con un trucchetto su body facciamo capire al file CSS su quale pagina siamo, per attivare lo stile current al menu e nei CSS i rispettivi stili ai stati del menu ovviamente con background-position dei CSS Sprites.\n\nCOMMENTI SUL SITO GRAZIE:e anche il link per scaricare i file\nhttp://obiv.it/video-giornale/6-css-sprites-menu.html\nhttp://obiv.it/\nALTRO sui CSS Sprites:\nhttp://www.webfab.it/css/60-design-con-css-sprites.html ', 240, 'KJFkzTT0Nvo', '2015-04-21 23:29:57'),
(25, 1, 25, 'CSS Sprites Parte2 (Creare Image Sprites) [OBIV].it', 'Seconda VideoLezione, del Numero 6 di [OBIV].it http://obiv.it/video-giornale/6-css-sprites-menu.html , e si continua a parlare dei CSS Sprites. Esattamente ora andiamo a creare i CSS Sprites in tre modi: dal Web con immagini già pronte, con Photoshop e immagini già pronte e per ultimo vediamo come creare un menu a quattro stati (normal,hover,active e current) da zero in Photoshop.\n\n\nCOMMENTI SUL SITO GRAZIE: e anche il link per scaricare i file\nhttp://obiv.it/video-giornale/6-css-sprites-menu.html\nhttp://obiv.it/\nALTRO sui CSS Sprites:\nhttp://www.webfab.it/css/60-design-con-css-sprites.html ', 240, 'I2G84nbybNY', '2015-04-21 23:29:57'),
(26, 1, 26, 'CSS Sprites Parte1 (Cosa? Dove? Perche? Quando?) [OBIV].it', 'In questa prima VideoLezione ,della serie nel Video Giornale 6 di [OBIV].it http://obiv.it/video-giornale/6-css-sprites-menu.html , vediamo che cosa sono i CSS Sprites, dove si applicano , dove servono, perché servono, perché sono un must have su un sito che si vuole far rispettare e per la domanda quando rispondo adesso: ORA!\n\n\nCOMMENTI SUL SITO GRAZIE:e anche il link per scaricare i file\nhttp://obiv.it/video-giornale/6-css-sprites-menu.html\nhttp://obiv.it/ ', 240, 'P9EjYYeZxCs', '2015-04-21 23:29:58'),
(27, 1, 27, 'MVC in PHP - 10 (Admin Menu - Visibile/Non Visibile) [OBIV].it', '(Model View Controller con PHP VideoCorso) - Iniziamo con questa VideoLezioni a creare il funzionale del nostro pannello amministrativo e partiamo dalla realizzazione della funzione rispondete alla visualizzazione dei menu, cioe impostiamo uno script che risponda alle azzioni del menu e lo facciamo grazie ai parametri GET e ocupiamoci a far funzionare il bottone visulizza/nascondi. ', 240, 'TB75JGNiY1I', '2015-04-21 23:29:58'),
(28, 1, 28, 'MVC in PHP - 11 (Admin Menu - Modifica,Elimina) [OBIV].it', 'Ora occupiamoci dei altri due bottoni del nostro pannello amministrativo "modifica" e "elimina" . La modifica procediamo a farla sulla stessa pagina in una form che comparira e carichera i dati gia esistenti. L''eliminazione deve avvenire quando spingiamo il bottone, e deve avvenire dopo una conferma che faremo nella prossima VideoLezione!!! ', 240, 't580gt-NkOs', '2015-04-21 23:29:58'),
(29, 1, 29, 'MVC in PHP - 12 (Eliminazione con conferma) [OBIV].it', 'Nell''ultima VideoLezione abbiamo fatto funzionare il bottono ''Elimina'' ma non abbiamo provveduto a richiedere una conferma di fronte a questa azione, cosa obbligatoria visto che sbagliare bottone capita a tutti. Quindi ecco due soluzioni con Javascript. In una usiamo confirm che mostra una finestrella del browser che richiede se eliminare o annulare e l''altra che mostra i bottoni Conferma , Annulla direttamente sotto al bottone Elimina. ', 240, 'f_05OxWhEl4', '2015-04-21 23:29:58'),
(30, 1, 30, 'MVC in PHP - 10.ripasso(HTML,CSS del pannello admin) [OBIV].it', 'Codice HTML e CSS dell pannello , come lo stilizzato io.\n\nE vi ricordo che condivido i file in dropbox con chi mi fa da referal!\nPassate dal link e registratevi: ', 240, 'rFIsySA-b9o', '2015-04-21 23:29:58'),
(31, 1, 31, 'MVC in PHP - 9 (Pannello Amministrativo- Gestione Menu) [OBIV].it', 'Passiamo alla seconda parte del sito che stiamo realizzando, ed è la parte del amministratore (beckend). Iniziamo dalla realizzazione della gestione dei menu. E facciamo in modo che in base alla visualizzazione che abbiamo(quindi frontend o beckend) il modello estragga dati diversi dal database, per capire a cosa serve questo alteriamo la tabella dei menu e aggiungiamoli un campo che determina se il punto menu e visibile sul sito o meno.\nCosi avremo sul sito, i punti menu che sono visibili, e nel pannello admin tutti i punti menu, con la possibilità di farli diventare visibili/invisibili , modificarli, cancellarli e crearli.\n\nPer informazioni,richieste,domande e altro commentate ... http://www.webfab.it/videotutorial/57-mvc-php-videocorso.html\nPero altri VideoCorsi e VideoLezioni http://obiv.it/videocorso-mvc-in-php.php ', 240, 'ubElSPzH_UM', '2015-04-21 23:29:58'),
(32, 1, 32, 'info Carlo.avi', 'http://obiv.it/ ', 240, 'lAb1IvTWRtI', '2015-04-21 23:29:58'),
(33, 1, 33, 'MVC in PHP - 8 (Content/testi) [OBIV].it', 'Creiamo il Modello, Controller e la Vista\ndella tabella che contiene i testi del sito,\nnel mio caso ''mvc_page''.\nEstraiamo i dati relativi al link che abbiamo cliccato nel menu\ne mandiamo in out-put testo,titolo,meta dati etc. \n\nNel video vi chiedo di farmi da referral in Dropbox , \ncosi condividiamo i file del VideoCorso. \nEcco il link: http://db.tt/swR2TFw\n-- Dropbox è una chiavetta virtuale di 2GB,\naccessibile con del software che si installa sul PC oppure\ntramite pannello WEB. ', 240, 'BPJ0sfBIRr0', '2015-04-21 23:29:58'),
(34, 1, 34, 'phpMyAdmin (Tema, Sessioni) [OBIV].it', 'i file e l-''articolo \r\n----http://www.webfab.it/php/58-cambiare-tema-phpmyadmin.html\r\nsessione\r\n---http://www.webfab.it/php/52-sessione-phpmyadmin.html\r\n\r\nphpMyAdmin uno strumento utilissimo e potentissimo per che lavora con i database, sopra tutto mySQL, ma il suo tema si lascia desiderare. Vediamo in questa videolezione come scaricare, modificare il tema e poi come prolungare la sessione ... http://www.obiv.it (Video Corsi e Video Lezioni) http://www.webfab.it (Trucchi, consigli, servizi, script, guide etc. per webmaster) ', 240, '7JkdU_m2xsk', '2015-04-21 23:29:58'),
(35, 1, 35, 'MVC in PHP - 7(Navigazione/menu)[OBIV].it', 'In questa VideoLezione del VideoCorso "MVC in PHP" andiamo finalmente a programmare un pò e faciamo la navigazione/menu del sito. Useremo il design pattern Model View Controller, dove come sappiamo il modello lavorera con la tabella del menu nel database, la vista mostrerà il risultato e il controller collegherà i due.\n\nI file delle video lezioni in dropbox, per chi mi fa il favore di fare da referal: http://db.tt/swR2TFw ', 240, 'Bdqf4nyVd5M', '2015-04-21 23:29:58'),
(36, 1, 36, 'MVC in PHP - 6(Tamplate HTML5 e CSS3)[OBIV].it', 'In questa video lezione  scriviamo il codice HTML e CSS (html5 e css3 per l''esattezza) necessario a fare una piccola struttura per il nostro sito.\r\n\r\nhttp://obiv.it/videocorso-mvc-in-php.php\r\n\r\nhttp://www.webfab.it/videotutorial/57-mvc-php-videocorso.html ', 240, 'crB60JZvK8k', '2015-04-21 23:29:58'),
(37, 1, 37, 'MVC in PHP - 5-DataBase(Ragioniamo,Disegniamo,Creiamo il DataBase) [OBIV].it', 'Diamo un''occhiata al disegnino del sito che andremo a fare.\nDecidiamo quale contenuto avrà e come saranno le tabelle nel database.\nDisegniamo queste tabelle e ci spostiamo su phpMyAdmin per crearle. ', 240, 'te8KUU36rAQ', '2015-04-21 23:29:58'),
(38, 1, 38, 'MVC in PHP - BONUS4 (Auto Config) [OBIV].it', 'La videolezione nella quale vediamo come fare in modo che lo script della connessione al db scelga automaticamente la configurazione, in base al host su cui siamo, locale o sul server web. Il Sito con tutte le video lezioni - http://obiv.it/  Sito con lezioni e consigli http://webfab.it/ ', 240, '0Adptme3OhI', '2015-04-21 23:29:58'),
(39, 1, 39, 'MVC in PHP -4(Configurazione,Connessione) [OBIV].it', 'Creiamo i file e le classi per la configurazione e connessione al database. Un po'' come nella video lezione sulla OOP http://obiv.it/video-giornale-n5.php che se non avete visto vi consiglio di guardarte almeno la prima parte. Buon proseguimento! ', 240, 'eDOwDXKJ3yM', '2015-04-21 23:29:58'),
(40, 1, 40, 'MVC in PHP -3 Ambiente(Server,Cartelle,File) [OBIV].it', 'Creaiamoci l''ambiente di lavoro: Impostiamo un virtual host in XAMPP, creiamo le cartelle (modules,views,controllers) per l''applicativo, il file index.php e .htaccess e altro.\nOfficial: http://obiv.it/videocorso-mvc-in-php.php\nDescrizione della MVC: http://www.webfab.it/videotutorial/57-mvc-php-videocorso.html ', 240, 'LC20sJYKgQo', '2015-04-21 23:29:58'),
(41, 1, 41, 'MVC in PHP -1 Intro(Cosa,Per chi,Come,Dove)? [OBIV].it', 'VideoCorso MVC in PHP [Videolezione Num. 1]. Introduzione al VideoCorso. Cosa faremo, cosa vedremo. Quali prerequisiti per iniziare, dove studiare? Come si svolgera il video corso, quali programmi useremo, dove scaricarli... \nOfficial PAGE con Lista Videolezioni e NewsLetter: \nhttp://www.obiv.it/video-corso/oop-mvc-php.html\ne http://www.webfab.it/videotutorial/57-mvc-php-videocorso.html ', 240, 'zf1EeNLv4Rc', '2015-04-21 23:29:58'),
(42, 1, 42, 'MVC in PHP -2(Cosè,perchè,come,esempio) [OBIV].it', 'VideoCorso MVC in PHP [Videolezione Num. 2]. Cosa vuol dire pattern architetturiale. Quale lo scopo della MVC( Modello Vista Controllo - Model View Controller ). Come funziona la MVC. Esempio dalla vita reale e esempio della MVC nel WEB. Che ruolo ha il modello (model). Che ruolo ha il Controllo (Controller).Che ruolo ha la vista (view). \nOfficial PAGE con Lista Videolezioni e NewsLetter: http://obiv.it/videocorso-mvc-in-php.php e http://www.webfab.it/videotutorial/57-mvc-php-videocorso.html ', 240, 'kuNn1wuzC0U', '2015-04-21 23:29:58'),
(43, 1, 43, 'PHP nei CSS [OBIV].it', 'Come usare codice, script, PHP al interno dei CSS, stili? Ci sono un paiio di metodi, configurare htaccess di Apache (aggiungendo gli stili css tra i file che devono essere processati da Zend con AddHandler application/x-http-php) o inviare intestazioni http con "header" in PHP. Pensate le semplificazioni che si possono avere grazie alle variabili e c''è tanto altro... ', 240, 'ZMVD2WsIrqk', '2015-04-21 23:29:58'),
(44, 1, 44, 'NetBeans IDE PHP  [OBIV]', 'Revisione del IDE Netbeans ', 240, 's9KeZKchyDM', '2015-04-21 23:29:58'),
(45, 1, 45, 'Notepad++ " text editor " [OBIV].it', 'Revisione di notepad plus plus Altre VideoLezioni e VideoCorsi su http://www.obiv.it/ ', 240, 'UZN6LltOMXk', '2015-04-21 23:29:58'),
(46, 1, 46, 'CodeLobster "wysiwyg editor"  [OBIV].it', 'Revisione del text editor code lobster ', 240, 'FhA1QY2bS98', '2015-04-21 23:29:58'),
(47, 1, 47, 'OOP PHP - Programmazione Orientata agli Oggetti in PHP [OBIV].it', 'Video Giornale [OBIV].it N.5 http://obiv.it/video-giornale/5-oop-in-php-esempio-database.html\n--------------------------------\nIn questo non corto videovedremo i concetti base della programmazione orientata agli oggetti "Object-oriented Programming" o più semplicemente OOP. Un tipo di programmazione con " classi " e " oggetti " grazie al quale si può riutilizzare codice scritto precedentemente senza il rischio di ripetere nomi delle variabili/funzioni. ---- In questa video lezione: nella prima mezzora vediamo come funziona la OOP con dei esempi semplici, dopo di che il restante della video lezione vediamo in pratica come si puo applicare la OOP in PHP costruendo due classi correllate per creare la connessione e l''interrogazzione al DataBase.  \n\n---- Altro sulla OOP in PHP lo potete trovare nel VideoCorso MVC in PHP nel quale costruiamo un Sito in OOP utilizzando il pattern MVC (Model View Controller). obiv.it/videocorso-mvc-in-php.php\n\n... http://www.obiv.it (Video corsi e Video lezioni) http://www.webfab.it (Trucchi, consigli, servizi, script, guide etc. per webmaster) ', 240, 'Sg3QiH-czmY', '2015-04-21 23:29:58'),
(48, 1, 48, 'XAMPP - Configurazione Prt. 2 "Server locale" [OBIV].it', 'Configuriamo XAMPP per attivare i virtual-host e avere domini virtuali sul PC. I siti potranno stare in qualsiasi cartella sul sito e essere raggiungibili da qualsiasi nome e senza il prefisso local host. Se riscontrate PROBLEMI leggete qui http://www.webfab.it/programmi/59-xampp-problemi-apache-vc9.html  \n\n... http://www.obiv,it (Video corsi e Video lezioni) http://www.webfab.it (Trucchi, consigli, servizi, script, guide etc. per webmaster) ', 240, 'Rd5GPjYFkcw', '2015-04-21 23:29:58'),
(49, 1, 49, 'XAMPP - Installazione Prt.1 ''Server Locale'' [OBIV].it', 'Installazione del web server XAMPP sulla macchina locale. Scarichiamo il pacchetto dal sito apachefriends, i link per altre versioni e per windows li potete trovare qua: http://www.webfab.it/programmi/43-server-web-locale-xamp.html . Poi installiamo il server vediamo come funziona e configuriamo il virtual-host cosi i nostri siti sul localhost avranno dei domini virtuali. Se riscontrate PROBLEMI leggete qui http://www.webfab.it/programmi/59-xampp-problemi-apache-vc9.html  \n\n... http://obiv.it/video-giornale-n3.php (Video corsi e Video lezioni) http://www.webfab.it (Trucchi, consigli, servizi, script, guide etc. per webmaster) ', 240, 'sSJkoUTnhzc', '2015-04-21 23:29:58'),
(50, 1, 50, 'Manuale PHP sul server locale [OBIV]', 'Quando si sviluppa, è utile avere un manuale PHP sul proprio computer. Chè contiene la documentazione delle funzioni di libreria, dei quali i link sono generati dal errore. ', 240, '4kRuD3hPBfA', '2015-04-21 23:29:58');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `jowa_videos`
--
ALTER TABLE `jowa_videos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `jowa_videos`
--
ALTER TABLE `jowa_videos`
  MODIFY `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=51;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
